.github/CONTRIBUTING.md, .gitignore, README.md, docs/about/collaborate.md, docs/about/contribute.md, docs/about/faq.md, docs/about/history-and-motivation.md, docs/about/pilot.md, docs/about/timeline.md, docs/meeting-minutes/2020.1.29-pilot-project-minutes.md, website/sidebars.json, website/siteConfig.js, website/yarn.lock
This pull request:
- Updates and re-organizes the README.md, and also moves content about how to contribute to .github/CONTRIBUTING.md
- Updates top and side navigate to 1) Add GitLab along with Github to top, 2) Add About to Top; 3) Create an about section of side menu
- Starting point folders of "About" md files (timeline, collaborate, faq, etc.)
- Starting point folder of "Meeting Minutes" including starting point notes for the 2019.1.29 kick-off minutes (for @aitana16 to complete)
=> Updated Information Architecture. Revised README / CONTRIBUTING.md

docs/get-involved/terms-of-service.md
Adding first draft get-involved/terms-of-service.md
=> Adding get-involved/terms-of-service.md

docs/get-involved/terms-of-service.md
Further edits to Terms of Service
=> Further edits to Terms of Service

docs/meeting-minutes/2020.1.29-pilot-project-minutes.md, docs/meeting-minutes/2020.2.12-pilot-project-minutes.md
=> Fixing IDs on meeting minutes

meeting-minutes/fx-options-wg/2020.4.23-fx-options-wg-meeting.md
=> Addition of agenda items for Fx Option WG 23Apr20

meeting-minutes/fx-options-wg/2020.4.23-fx-options-wg-meeting.md
=> Switching order of agenda items 1 and 2.

meeting-minutes/fx-options-wg/2020.4.23-fx-options-wg-meeting.md
=> Meeting minutes added

meeting-minutes/fx-options-wg/2020.4.30-fx-options-wg-meeting.md
@aitana16 - could you cross check the attendees list in case any need to be added? Thanks
=> Meeting minutes and action items added for 30Apr20

meeting-minutes/fx-options-wg/2020.5.7-fx-options-wg-meeting.md
@aitana16 - Agenda for 7thMay meeting
=> 2020.5.7-fx-options-wg-meeting.md

meeting-minutes/commodities-ref-data-wg/2020.5.6-commod-wg-meeting.md
=> Agenda - Commodities WG Meeting - 06/05/20

meeting-minutes/fx-options-wg/2020.5.7-fx-options-wg-meeting.md
=> Updating with meeting minutes

meeting-minutes/fx-options-wg/2020.5.14-fx-options-wg-meeting.md
=> Adding agenda for meeting 14May20

meeting-minutes/fx-options-wg/2020.5.14-fx-options-wg-meeting.md
=> Adding agenda item

meeting-minutes/fx-options-wg/2020.5.14-fx-options-wg-meeting.md
=> Adding minutes of meeting

meeting-minutes/commodities-ref-data-wg/2020.5.13-commod-wg-meeting.md
=> Minutes update 13/05

meeting-minutes/commodities-ref-data-wg/2020.5.20-commod-wg-meeting.md
=> Minutes Update 2005

meeting-minutes/fx-options-wg/2020.5.21-fx-options-wg-meeting.md
=> Slight tweaks

meeting-minutes/fx-options-wg/2020.5.28-fx-options-wg-meeting.md
=> Minutes added from meeting

meeting-minutes/fx-options-wg/2020.6.11-fx-options-wg-meeting.md
=> Adding Agenda

meeting-minutes/fx-options-wg/2020.6.11-fx-options-wg-meeting.md
@aitana16 - if you can also add in attendees will be great, thanks!
=> Meeting Minutes

README.md
Updating to the newly created forming lifecycle badge until initial contribution into incubation.
=> Updating to forming lifecycle stage

website/static/css/home-page.css, website/static/index.html, website/static/under-construction.html
@maoo @brooklynrob @gs-bracej could you please review and merge this fix. Thank you!
=> fix initial zoomed in view of home-page on iOS

README.md
Fix broken link in words "This Repository"
=> Fix broken link in words This Repository

CONTRIBUTING.md
Hi,
Just updating the guide to match the actual user email format Github uses, to avoid any potential confusion for newcomers. Also a simpler git command to check the user.email property.
=> Minor clarifications / simplification for getting started guide

docs/getting-started/installation-guide.md
Updated command used to start the legend-engine server locally
=> Updated command used to start the legend-engine server locally

CODEOWNERS
add david.harte-gs to codeowners
=> add david harte to codeowners

installers/docker-compose/README.md, installers/docker-compose/legend-studio-dev/docker-compose.yml, installers/docker-compose/legend-studio-dev/scripts/run-engine.sh, installers/docker-compose/legend-studio-dev/scripts/run-sdlc.sh, installers/docker-compose/legend-studio-dev/scripts/setup.sh, installers/docker-compose/legend-with-remote-gitlab/docker-compose.yml, installers/docker-compose/legend-with-remote-gitlab/scripts/setup.sh, installers/docker-compose/legend/docker-compose.yml, installers/docker-compose/legend/scripts/setup.sh, installers/docker-compose/shared/templates/sdlc/dev-config.yml
Fix https://github.com/finos/legend/issues/390
Also, address the change in https://github.com/finos/legend-sdlc/pull/138 to make Studio development setup smoother
=> Docker compose minor improvements

docs/studio/review-process.md, website/package.json, website/pages/en/releases.js, website/yarn.lock
Recovery from https://github.com/finos/legend/pull/398. I forgot to push this change 🙇
=> Fix the broken website build

.github/workflows/docusaurus.yml
@maoo @epsstan could one of you approve this so we can trigger the build for the website? I suspect if this does trigger the build for the website upon merge. If it doesn't, could you help us manually trigger it @maoo ? Or could you grant me and Ephrim some right that can allow us to manually trigger actions for this repo? Thanks!!
=> update doc publish action to watch release directory

docs/language/legend-language.md
- Fix constraint name to be intuitive.
=> Fix constraint name in doc.

docs/language/released-functions.md, docs/language/upcoming-functions.md
Update function reference docs
=> Update function reference docs

website/static/resource/studio/documentation.json
- Update doc for Persistence and PersistenceContext
- Fix a few typos
=> Update static documentation for persistence DSL.

CODEOWNERS
=> Removing myself as codeowner

README.md, docs/getting-started/installation-guide.md
- fix broken link
- Remove what looks like merge artefacts from installation guide + attempt to fix unrendered emoji
=> Tidy up some docs

v2-website/docusaurus.config.js, v2-website/static/css/home-page.css
Documentation Homepage styling and config fix
=> Documentation Homepage Fix 

.github/workflows/docusaurus.yml, build-site.sh
Switching to V1 to first fix some performance issues in page loading/homepage display
=> Rollback to V1

.github/workflows/docusaurus.yml, releases/2021-02-03/manifest.json, releases/2021-02-08/manifest.json, releases/2021-02-09/manifest.json, releases/2021-02-12/manifest.json, releases/2021-02-17/manifest.json, releases/2021-02-18/manifest.json, releases/2021-03-03/manifest.json, releases/2021-03-09/manifest.json, releases/2021-03-12/manifest.json, releases/2021-03-15/manifest.json, releases/2021-03-16/manifest.json, releases/2021-03-18/manifest.json, releases/2021-03-22/manifest.json, releases/2021-03-24/manifest.json, releases/2021-03-26/manifest.json, releases/2021-03-31/manifest.json, releases/2021-06-09/manifest.json, releases/2021-07-08/manifest.json, releases/2021-10-18/manifest.json, releases/2022-04-26/manifest.json, releases/2022-05-05/manifest.json
Putting back releases folder in home directory for v1 of website
=> Restore releases folder 

.github/workflows/docusaurus.yml, docs/community/get-help-from-community.md, docs/showcases/LogicalModellingBasic.md, docs/tour/tour.md, releases/2021-02-03/manifest.json, releases/2021-02-08/manifest.json, releases/2021-02-09/manifest.json, releases/2021-02-12/manifest.json, releases/2021-02-17/manifest.json, releases/2021-02-18/manifest.json, releases/2021-03-03/manifest.json, releases/2021-03-09/manifest.json, releases/2021-03-12/manifest.json, releases/2021-03-15/manifest.json, releases/2021-03-16/manifest.json, releases/2021-03-18/manifest.json, releases/2021-03-22/manifest.json, releases/2021-03-24/manifest.json, releases/2021-03-26/manifest.json, releases/2021-03-31/manifest.json, releases/2021-06-09/manifest.json, releases/2021-07-08/manifest.json, releases/2021-10-18/manifest.json, releases/2022-04-26/manifest.json, releases/2022-05-05/manifest.json
Restoring overwritten links and turning them into the standard [link](https://link) format.
=> Add back links in docs

.github/workflows/docusaurus.yml, build-site.sh, v2-website/.docusaurus/docusaurus.config.mjs, v2-website/build/index.html, v2-website/docusaurus.config.js, v2-website/static/css/docs.css, v2-website/static/css/home-page.css, v2-website/static/css/releases.css, v2-website/static/css/variables.css
=> Switching back to V2 with light mode styling edits

v2-website/docusaurus.config.js
Switch search config for algolia
=> Switch search config

docs/showcases/graphql.md, docs/showcases/overview.md, website/sidebars.json
=> Add GraphQL Showcase

v2-website/sidebars.json
=> Add sidebars for showcases

docs/showcases/graphql.md
=> Update graphql showcase docs

docs/showcases/overview.md, docs/tutorials/graphql-tutorial.md, v2-website/sidebars.json
Rename 'showcase' to 'tutorial'
=> Rename 'showcase' to 'tutorial'

website/docusaurus.config.js
=> Turn on contextual search

website/static/resource/studio/documentation.json, website/static/resource/studio/documentation/pure-ide.json, website/static/resource/studio/documentation/studio.json
Fixing the .json doc files to align keys properly with https://github.com/finos/legend-studio
=> Fix: documentation keys

website/docusaurus.config.js, website/static/css/variables.css
=> Add search to docs

docs/showcases/showcase-projects.md
update showcase projects table to organize by feature (vs previous organization by user journey)
=> re-org showcase projects by feature

installers/omnibus/README.md, installers/omnibus/scripts/start.full.sh, installers/omnibus/scripts/start.gitlab-oauth.sh, installers/omnibus/scripts/start.gitlab-pat.sh, installers/omnibus/scripts/start.sh
=> omnibus: add troubleshooting section

showcases/data/Stores/Relational Store/Connection/BigQuery/DefaultCredentials/code.pure, showcases/data/Stores/Relational Store/Connection/BigQuery/DefaultCredentialsWithProxy/code.pure, showcases/data/Stores/Relational Store/Connection/BigQuery/IdentityFederation/code.pure, showcases/data/Stores/Relational Store/Connection/BigQuery/IdentityFederationWithScopes/code.pure, showcases/data/Stores/Relational Store/Connection/Databricks/code.pure, showcases/data/Stores/Relational Store/Connection/Spanner/code.pure, showcases/data/Stores/Relational Store/Connection/Trino/code.pure, showcases/data/Stores/Relational Store/Database Specification/Basic/code.pure, showcases/data/Stores/Relational Store/Database Specification/Filter/code.pure, showcases/data/Stores/Relational Store/Database Specification/Include/code.pure, showcases/data/Stores/Relational Store/Database Specification/Join/Basic/code.pure, showcases/data/Stores/Relational Store/Database Specification/Join/Self Join/code.pure, showcases/data/Stores/Relational Store/Database Specification/Milestoning/Bitemporal/code.pure, showcases/data/Stores/Relational Store/Database Specification/Milestoning/Business/code.pure, showcases/data/Stores/Relational Store/Database Specification/Milestoning/Processing/code.pure, showcases/data/Stores/Relational Store/Database Specification/Schema/code.pure, showcases/data/Stores/Relational Store/Database Specification/View/code.pure, showcases/data/Stores/Relational Store/Mapping/Distinct/code.pure, showcases/data/Stores/Relational Store/Mapping/Embedded/Inline/code.pure, showcases/data/Stores/Relational Store/Mapping/Embedded/Otherwise/code.pure, showcases/data/Stores/Relational Store/Mapping/Extends/code.pure, showcases/data/Stores/Relational Store/Mapping/Filter/code.pure, showcases/data/Stores/Relational Store/Mapping/GroupBy/code.pure, showcases/data/Stores/Relational Store/Mapping/Include/Basic/code.pure, showcases/data/Stores/Relational Store/Mapping/Include/Store Substitution/code.pure, showcases/data/Stores/Relational Store/Mapping/Joins/Basic/code.pure, showcases/data/Stores/Relational Store/Mapping/Joins/Chained/code.pure, showcases/data/Stores/Relational Store/Mapping/Scope/code.pure, showcases/src/test/java/org/example/ShowcaseCompilerTest.java
Adds compilation as a phase to Showcase tests to ensure that they can be run out of the box.
Scope in Mapping cannot be run directly as roundtrip string-replaces the scope. It is kept as a comment to highlight the functionality.
=> Add Compilation phase to Showcase tests

installers/omnibus/variants/ghc/build.sh
Update the docker image name on GHC build script
=> Update the docker image name on GHC build script

installers/ghc/src/main/java/org/finos/legend/stack/LegendAwsStack.java, installers/ghc/src/main/java/org/finos/legend/stack/LegendAwsStackWithAuth.java, installers/omnibus/.env
1/ Bump version # of omnibus release 
2/ Add omnibus properties
=> Update Grace Hopper Omnibus

showcases/data/End-to-end examples/Integrate Mappings/code.pure, showcases/data/End-to-end examples/Integrate Mappings/info.md
Dependent upon new legend-engine version
=> WIP: New Showcase: Integrate Consumer and Producer Mappings

showcases/data/Store/Relational Store/Service/Basic/code.pure
update dataspace to contain template query in relational-store showcase
=> update dataspace to contain template query in relational-store showcase

showcases/data/Store/Relational Store/Service/Basic/code.pure, showcases/pom.xml
add id in template query in dataspace
=> add id in template query in dataspace and update engine@4.43.3

showcases/data/Store/Relational Store/Query/code.pure, showcases/data/Store/Relational Store/Query/info.md, showcases/pom.xml, showcases/src/test/java/org/example/ShowcaseCompilerTest.java
Querying Relational Store using Relation Functions
Requires - https://github.com/finos/legend-engine/pull/2826
=> add showcase relation example

showcases/data/Store/Relational Store/Service/Basic/code.pure
improve execution context key for northwind showcase
=> improve execution context key for northwind showcase

showcases/data/Model/Document and share your model/Data Space With Exectuables/code.pure, showcases/data/Model/Document and share your model/Data Space/code.pure
=> clean dataspace showcase

showcases/data/Model/Leverage profiles in your model/Stereotypes/code.pure, showcases/data/Model/Leverage profiles in your model/Stereotypes/info.md, showcases/data/Store/Relational Store/Mapping/Joins/Filter Mapping/code.pure, showcases/data/Store/Relational Store/Mapping/Joins/Filter Mapping/info.md
Adding showcase projects to demonstrate stereotyping and filter mapping
=> stereotype and filter mapping showcases

showcases/data/Essential/Functions/Date/Basic/code.pure, showcases/data/Essential/Functions/Date/Basic/info.md
Adding showcase for string to date functionality
=> Review date showcase

showcases/data/Model/Document and share your model/Data Space With Exectuables/code.pure, showcases/data/Store/Relational Store/Service/Basic/code.pure, showcases/pom.xml
update dataspace template query showcase
=> update dataspace template query showcase

meeting-minutes/pilot-project-meeting-minutes/2020.3.11-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.3.25-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.4.22-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.4.8-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.5.20-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.5.6-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.6.17-pilot-project-minutes.md, meeting-minutes/pilot-project-meeting-minutes/2020.6.3-pilot-project-minutes.md
Removing meet pass in md files
=> Removing meet pass in md files

showcases/data/Essential/Functions/Date/Basic/code.pure, showcases/data/Model/Build a data model/code.pure, showcases/data/Store/Relational Store/Database Specification/Tabular Function/code.pure, showcases/data/Store/Relational Store/Database Specification/Tabular Function/info.md, showcases/data/Store/Relational Store/Query/code.pure, showcases/pom.xml, showcases/src/test/java/org/example/ShowcaseCompilerTest.java
=> Add Tabular function showcase

.github/workflows/publish-website.yml
Reverts finos/legend#859
need to refine action to address error
=> Revert "update PCT Report as part of website publication"

showcases/pom.xml
=> update legend engine version
