docs/meeting-minutes/2020.2.12-pilot-project-minutes.md
Removed link in 2020.2.12 meeting minutes to 2019.1.29 which was causing an error in the build process.
=> Removed link in 2020.2.12 meeting minutes to 2019.1.29

website/static/index.html, website/yarn.lock
This pull request adds Google Analytics code `UA-89349362-7` to the Alloy microsite in the `index.html` only due to this page being built outside the Docusaurus framework.
The following `gaTrackingId` javascript was added to the head of `index.html`. This adds the GA code to the homepage of the microsite only.  Inner pages are served through `siteConfig.js`
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-89349362-7', 'auto');
ga('send', 'pageview');
</script>
```
The commit also includes an …
=> Add Google Analytics to Alloy homepage

meeting-minutes/fx-options-wg/2020.4.16-fx-options-wg-meeting.md
@aitana16
Action Items for Fx Option WG 16Apr20:
Ted - to put together examples with Vijay (re barriers) to share with the group in the next session, particularly regarding:
1. buyer/seller attributes
2. put/callCurrencyAmount classes - representation in the CDM FxOption model. 
Ted - to review *number* vs *float* type in CDM e.g. strike and trigger class appear as float. [21Apr - confirmed offline basicType *number* in CDM is equivalent to *float*. Vijay and team - to update in AlloyStudio.] 
Vijay - to follow up suggestion from group around adding a function which auto-arranges a diagram.
Vijay - to add to agenda for next session how to navigate different code formats.
All - to have a go at modelling any suggestions in AlloyStudio and to get familiar with the tools features.
=> Addition of meeting minutes/action items from WG held on 16Apr

website/siteConfig.js
When i forked legend to try and fix an issue over on ODP https://github.com/finos/open-developer-platform/issues/181
I found the Github Action was not working, i think it was because of the project slug(name) in the config file.
Changing this on my fork allows the action to pass.
You can see the error here: https://github.com/adamj-codethink/legend/pull/1
=> rename project slug in config file

installers/aws-docker/install/NOTES.md, installers/aws-docker/install/gitlab/Dockerfile, installers/aws-docker/install/gitlab/build.sh, installers/aws-docker/install/gitlab/config.sh, installers/aws-docker/install/run-gitlab.sh
Before this patch we used a workaround taken directly from
https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/2837#note_109602925,
however the workaround is far more involved than it needs to be.
Instead of setting `ENV` in a Dockerfile, we can simply set an
environment variable on the CLI with the same effect, saving users the
time it takes to build a docker image, as well as the maintenance
overhead of running a custom build script for updates.
----
Sorry for the direct patch here; but it's a tiny thing so I don't
think it needs to go through issues :)
If you think the doc is still needed to point out public signup is
disabled, please do tell.
=> Don't rebuild the GitLab docker image to set an environment variable

docs/installation/hosted-finos.md, docs/installation/maven-install.md
Update Maven installation guide to follow the latest `sdlc`, `engine`, and `studio` codebase.
We still need to update the config templates from these respective repositories to make this PR effective. Track:
https://github.com/finos/legend-sdlc/pull/129
https://github.com/finos/legend-engine/pull/171
https://github.com/finos/legend-studio/pull/133
=> Update Maven installation guide

installers/aws-docker/install/templates/studio/uiConfig.json, installers/docker-compose/shared/templates/studio/uiConfig.json
This is to accommodate for the latest version of Studio [finos/legend-studio:0.2.27](https://hub.docker.com/layers/finos/legend-studio/0.2.27/images/sha256-f971b089918b9314fd0e5d7c070d2236864e359448e66261f1d65e51bd051a8d?context=explore) whose config now expects `metadata` field to be filled
=> Update studio config to prepare for metadata server

releases/2021-02-03/manifest.json, releases/2021-02-08/manifest.json, releases/2021-02-09/manifest.json, releases/2021-02-12/manifest.json, releases/2021-02-17/manifest.json, releases/2021-02-18/manifest.json, releases/2021-03-03/manifest.json, releases/2021-03-09/manifest.json, releases/2021-03-12/manifest.json, releases/2021-03-15/manifest.json, releases/2021-03-16/manifest.json, releases/2021-03-18/manifest.json, releases/2021-03-22/manifest.json, releases/2021-03-24/manifest.json, releases/2021-03-26/manifest.json, releases/2021-03-31/manifest.json, releases/2021-06-09/manifest.json, website/pages/en/releases.js
We add `timestamp` field to manifest. This will help with future releases that might not follow the current convention (e.g. `2021-02-02-hotfix, 2021-02-02.2` etc.). Also, we can use this timestamp field to sort the release (latest first).
=> Minor improvement to release page and create new release 2021-06-09

docs/installation/maven-install.md
The last section in Maven installation page should be
setup legend-studio.
Signed-off-by: Kejia Hu <kejia.hu@codethink.co.uk>
=> Fix a typo

installers/docker-compose/legend-studio-dev/scripts/setup.sh, installers/docker-compose/legend-with-remote-gitlab/scripts/setup.sh, installers/docker-compose/legend/scripts/setup.sh
The Docker-compose-based installers overwrite the COMMANDs in the
container images of the Engine and SDLC components with some scripts
which handle some setup tasks before starting the actual services.
Part of the setup stepts these scripts do is attempting to run a
`gen-config.sh` script they assume is located in `/scripts`, but the
various pre-Docker-compose scripts accidentally copy `gen-config.sh`
into a subdirectory also called '/scripts'. (thus, inside the containers,
the actual path would be '/scripts/scripts/gen-config.sh')
This patch ensures that all of the scripts required by the Engine and
SDLC containers are located under the single '/scripts' directory as
was originally intended.
=> Fix Docker-compose installers '/scripts' volume structure.

README.md
The current `contribute-to-legend` page on the Legend microsite is displaying a `404 Error` when browsing from the Legend `README.md`.  
This pull request updates the following link to resolve the issue. 
```
["contribute to Legend"](https://legend.finos.org/docs/getting-started/contribute-to-legend)
```
```
["contribute to Legend"](https://legend.finos.org/docs/contribute/contribute-to-legend)
```
=> Fix Legend Microsite Contribute Link

website/static/resource/studio/documentation.json
This partially reverts https://github.com/finos/legend/pull/538
We can remove this file when we completely migrate over
=> Add back legacy Studio documentation till we migrate

v2-website/static/indexBackup.html
Removing `index.html` file to fix homepage different rendering.
=> Documentation homepage fix 

website/docusaurus.config.js, website/package.json
This PR uses the [Docusaurus gtag plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) to update the website to the latest version of Google Analytics (GA4).
=> Configure GA4

installers/omnibus/scripts/start.gitlab-pat.sh
Without this, the error below was being hit on my Ubuntu VM box 
```
docker: error during connect: Post "http://docker:2375/v1.24/containers/create": dial tcp: lookup docker on 192.168.1.1:53: no such host.
```
OS version info:
```
root@workvm-july:/home/user# uname -a
Linux workvm-july 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
Related information page: https://releasecandidate.dev/posts/2021/how-to-fix-docker-no-such-host-port-53/
=> Update start.gitlab-pat.sh to mount docker.sock for nested container

showcases/src/test/java/org/example/ShowcaseCompilerTest.java
Strips out comments to avoid discrepancies with compiler comment stripping.
Skips tests if input file is empty.
=> Strengthen Showcase tests

.github/workflows/check-showcases.yml
Restricts types of pull request events that can trigger this action.
Runs tests only for changed paths detected by git.
=> Run only changed showcases on PR

.github/workflows/legend-release.yml, scripts/compute-version.sh
This PR:
1. Uplift stack release workflow to auto-compute versions based on major/minor/patch release
2. Increase time-out for maven central artifact check
=> Uplift stack release workflow to auto-compute versions

showcases/data/Store/Mongo Store/code.pure, showcases/data/Store/Mongo Store/info.md
showcase project shwoing how to connect to and query a mongoDB
=> adding showcase for mongodb

showcases/data/Store/Relational Store/Mapping/Semi Structure/Basic/code.pure, showcases/data/Store/Relational Store/Query/code.pure
Updating relational showcases and fixing TDS path
=> Updating relational showcase

.github/workflows/publish-website.yml
update PCT Report as part of website publication
=> update PCT Report as part of website publication

docs/community/legend-pct-howto.md
remove legend-pure refs to simplify
=> remove legend-pure refs to simplify

showcases/data/Essential/Functions/Standard/code.pure, showcases/data/Essential/Functions/Standard/info.md, showcases/pom.xml
add showcase and update engine version to 4.89.2
=> add showcase and update engine version to 4.89.2

showcases/data/End To End Examples/Integrate Mappings/code.pure
fix for integrate-mappings showcase
=> fix for integrate-mappings showcase
